### ISSUE TITLE
Concent fails with 500

### ISSUE THREAD

**Issue by jiivan** [golemfactory/concent#108]
```
Prepared message: ForceReportComputedTask(header=MessageHeader(type_=4001, timestamp=1518194315, encrypted=False), sig=None, slots=[['task_to_compute', TaskToCompute(header=MessageHeader(type_=2002, timestamp=1518194315, encrypted=False), sig=None, slots=[['requestor_id', None], ['requestor_public_key', None], ['provider_id', None], ['provider_public_key', None], ['compute_task_def', {'task_id': 'a1', 'subtask_id': 'a1/1', 'deadline': 1518194325}]])], ['result_hash', 'sha1:6597eb6497f74f425c7ebacd712562cc9234697e']])
Sending to concent...
2018-02-09 17:38:35 DEBUG    golem.network.concent.client        send_to_concent(): Encrypting msg ForceReportComputedTask(header=MessageHeader(type_=4001, timestamp=1518194315, encrypted=False), sig=None, slots=[['task_to_compute', TaskToCompute(header=MessageHeader(type_=2002, timestamp=1518194315, encrypted=False), sig=None, slots=[['requestor_id', None], ['requestor_public_key', None], ['provider_id', None], ['provider_public_key', None], ['compute_task_def', {'task_id': 'a1', 'subtask_id': 'a1/1', 'deadline': 1518194325}]])], ['result_hash', 'sha1:6597eb6497f74f425c7ebacd712562cc9234697e']])
2018-02-09 17:38:35 DEBUG    golem.network.concent.client        send_to_concent(): data: b'\x0f\xa1\x00\x00\x00\x00Z}\xce\x8b\x01\xb4\xe1\xeb\xe2e\x13\xa1\xb6\xd5e\xee\x95\xddj\xe2R\xc5<\x0f\x05W\xd4R\xa5\xd7\x1aX\xf4k)\xf5[V\xbc\xd7\x06\x1d\xbe3D\xd6\x9f<\x08T\xb9\x97\x87\xfc\xad\x0e\x98`Tf}?X\xff=\xdd\xd0\xbf@\x00\x04(<~|\x99\x83\xa29s\xba\x94\xee\xdfW\x97\xd3Vm\xc0\xeb\x1c\xe8\xe8{\xa8\x03\xfbD\x7f\xf6\x8a&M\xc6f?\x1c\x87{\x0c\r\x0b\x17o$h\x85\x8fW1\xc0\x02\x9cV\x87\x81\xea_Y5.2\x9a\x01(M\x83e\xfc\xa7\x90\x1c\x18$\x8c\x91\xbd\xa3/\xbc\xaf`\x87z\xfa\xf9\xd4\xe1C\x9f\xcb\xa7Ub1dT\x8ck\x0f\x8f\x04!\x1d\x1f\xc7\xd8m\x9c\xe5\x1e\x82\xe3\xdd\x99h\xf9#\x7f\xc0\xac\x1dw\xcd5\xa3\xfd\xb7\xca\x00\x1e\t\xa3\xf4\x94\xf7\x17\xfe\xc9*\x8a@\xd1\xc8\x1fj\xdd\x1d_O\x8e;\x93\xf3\xc6J&\xdd<\x16\xa0\xa2\xfa\xc7\x08\x03\xaaT\xfd\x05\x92\x88B\x07^\x83I\xdc"\xb1\xbf\xc9/$"hRJ\xd3\xb7\x0b\xe3\xec\xcc\x7f\xcb\x99\xb7P\xcd}\xfd\xde\xc3,\xe3\xca\xf2\xcf{a\x89>\xad\xc7F\x9d\xf0\x98\x81\xa0=8\x000 [`F(\xabW\x07j\xbd0\xf44\t2\xc20\x8aX/eg\x9fjV\xdc\xf6\x81$)\xf3g\x9a@%\x8a5o+?\x81u\xc9\x00K\x01O6\x8a\xb3\xef\xaa*\xb8\x1e8\x9a\x88l\xbc\x9aj\xdc\x8b\x92\tD\x17Xd\x90Rm\xae\'\xaf\x0f\x0e\xe9x\xe4\x02\xda\xca\x16\x91h\xca\xef9\x9b,$M\xf2.\x8a\xed\xb15\x90lj\xaf\xbbS{\x16@\x81\x85$i|\xbe\xee\xdf\x1e\x83\xef:\xa2\xf0g\xaa\xf7\n\xfb\xd3T\x91HP\x11Du*\'3\x18^\x11a\x8d\xebU$\x8cM\x10g$\x1f\xa1>\xc6\x88\x13\x15P\xa62\xf4\xad\xc0\xd2\xfa73\xf9`A\xff\xa6\xef\xd9\xb2w\xd2]4'
2018-02-09 17:38:35 DEBUG    golem.network.concent.client        send_to_concent(): POST 'http://staging.concent.golem.network/api/v1/send/' hdr: {'Content-Type': 'application/octet-stream', 'Concent-Client-Public-Key': b'4jfyds5xqBUW4+kDg10lMxSjCT329e3oKVFNDFRLa0ipyO9iCLQ1+pzZ/MXtcyHBr0WjqRNaTtcPowu9g5XRbQ==', 'X-Golem-Messages': '1.7.0'}
2018-02-09 17:38:37 DEBUG    golem.network.concent.client        Headers received from Concent: {'Server': 'nginx/1.13.6', 'Date': 'Fri, 09 Feb 2018 16:38:37 GMT', 'Content-Type': 'text/html', 'Content-Length': '27', 'Connection': 'keep-alive', 'Vary': 'Cookie', 'Concent-Golem-Messages-Version': '1.6.0', 'X-Frame-Options': 'SAMEORIGIN'}
2018-02-09 17:38:37 WARNING  golem.network.concent.client        Concent failed with status 500 and body: '<h1>Server Error (500)</h1>'
Traceback (most recent call last):
  File "./scripts/test-concent.py", line 38, in <module>
    main()
  File "./scripts/test-concent.py", line 31, in main
    content = client.send_to_concent(msg, keys.raw_privkey, keys.raw_pubkey)
  File "/home/dybi/repo/golem81/golem/network/concent/client.py", line 65, in send_to_concent
    response.text
golem.network.concent.exceptions.ConcentServiceException: Concent service exception (500): <h1>Server Error (500)</h1>
```

**Comment by cameel** [comment]
This is probably an issue with deployment. I think we still had the old version there. I've redeployed it. Please try again now.

**Comment by rwrzesien** [comment]
@cameel @jiivan Can this one be closed ?

**Comment by cameel** [comment]
We have deployed 0.3 today. I have just sent out the notification. We can close it when @jiivan confirms that this particular error does not happen for him.
