### ISSUE TITLE
TypeError when a client key in TaskToCompute is empty

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent#180]
Error happens for example when we send AckReportComputedTask, but nested TaskToCompute have empty `provider_public_key` field. Then in `store_pending_message()` method we're trying to  create Client using empty key, which ends in crush. `store_pending_message()` takes `client_public_key` form a lot of different sources, so we're going to need some additional validation.

```python
13:05:40 ERROR    | Internal Server Error: /api/v1/send/
Traceback (most recent call last):
  File "/home/jakub/.virtualenvs/test/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/jakub/.virtualenvs/test/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jakub/.virtualenvs/test/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/jakub/.virtualenvs/test/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jakub/Documents/work/projects/concent/concent_api/utils/api_view.py", line 75, in wrapper
    response_from_view = view(request, message, *args, **kwargs)
  File "/home/jakub/.virtualenvs/test/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/jakub/Documents/work/projects/concent/concent_api/core/views.py", line 42, in send
    logging.log_message_received(
  File "/home/jakub/Documents/work/projects/concent/concent_api/core/views.py", line 217, in handle_send_ack_report_computed_task
    subtask             = subtask,
  File "/home/jakub/Documents/work/projects/concent/concent_api/core/views.py", line 858, in store_pending_message
    client          = Client.objects.get_or_create_full_clean(client_public_key)
  File "/home/jakub/Documents/work/projects/concent/concent_api/core/models.py", line 44, in get_or_create_full_clean
    instance = self.get(public_key = base64.b64encode(public_key))
  File "/home/jakub/.virtualenvs/test/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'NoneType'
13:05:40 ERROR    | "POST /api/v1/send/ HTTP/1.1" 500 120078
```

**Comment by cameel** [comment]
Yeah, we need a validation for that. It should result in a HTTP 400, not a crash. The key should be a string and should have the correct length.

Remember to validate both provider's and requestor's key.
