### ISSUE TITLE
api-integration-force-get-task-result-test.py is not working

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#278]
When running `api-integration-force-get-task-result-test.py`:

```
python api-integration-force-get-task-result-test.py http://127.0.0.1:8000
11:04:52 INFO     | Raven is not configured (logging is disabled). Please see the documentation for more information.
File has not been stored on cluster
SEND (http://127.0.0.1:8000/api/v1/send/)
MESSAGE:
    type                           = ForceGetTaskResult
    timestamp                      = 1523876692
    encrypted                      = False
    sig                            = None
    header                         = MessageHeader(type_=4009, timestamp=1523876692, encrypted=False)
        type                           = ReportComputedTask
        timestamp                      = 1523876692
        encrypted                      = False
        sig                            = None
        address                        = None
        computation_time               = None
        eth_account                    = None
        extra_data                     = None
        header                         = MessageHeader(type_=2004, timestamp=1523876692, encrypted=False)
        key_id                         = None
        multihash                      = None
        node_info                      = None
        node_name                      = None
        options                        = None
        package_hash                   = sha1:07082a1cdfae09e901b24ba68ad4321306529dc7
        port                           = None
        result_type                    = None
        secret                         = None
        size                           = 18
            type                           = TaskToCompute
            timestamp                      = 1523876692
            encrypted                      = False
            sig                            = b'\xb9\x00\xd6\x0crn\xd8[4\xd8N\xff\x8cP\xd3\xba\xab\x880\xc5(\xcbuR\xf84\x18?\x88\xe1"xQ`\xb8<\x10\xf0\xe7p\x8dx\x05\x99\x0b\xac?o\x1e\x85\xf6@\x01\xd1\xbf\x9eI\xa1\xee\xb2\xe7\x015X\x01'
            compute_task_def               = {'task_id': '85633existing_file', 'subtask_id': '85633', 'deadline': 1523891092}
            concent_enabled                = True
            header                         = MessageHeader(type_=2002, timestamp=1523876692, encrypted=False)
            package_hash                   = None
            price                          = 0
            provider_ethereum_public_key   = None
            provider_id                    = None
            provider_public_key            = b'B\x92\x1b\xff\xc6\xbd%/\xd0\x86\xfa\xd1\xc6o\xd1T\xcewT\x88\x8bK$\xf4RA\x18\xa7)\x98\xec\x18C<\xfc\xec\xd1\xbf8\na\xb0&\xb3x\x15\xb9v\xc7\x9b\xec\x08"\xf2\x0f\xf4\xbd\\N\xde-\x85\xdeg'
            requestor_ethereum_public_key  = None
            requestor_id                   = None
            requestor_public_key           = b't@\x92\xe2\x03\x933j\xc4\x13\x11_+\xa6|}\xfe\xc5;\xa2\xd1\xed\xa8\xe3x\xa7\x83\xc1\x0b\x9b\x88\xb5GMN\xcc\xd9\x86\xac\xc3n~\xc1\x13\xee[\xf5-\xff\x96A+r\xb5:\xb3O\xd4\x14v)\xf7\x82\xea'
STATUS: 200 OK
MESSAGE:
Concent-Golem-Messages-Version = 2.3.1
    type                           = AckForceGetTaskResult
    timestamp                      = 1523876692
    encrypted                      = True
    sig                            = b'\xb4\xb4?\xe1\xda\xf5\x9e\xbd\xdf\xa0\xedy\xab\xb6?=\x15\x81\xf6\xf6\xa9\x0eB\x17\xf2;s8\x0bB\x00\xbdYC\x1e\x03\x11\xecl\xc8\x87\x86\xf3\x1d\x8c41\xdfe\xe8wu?!\xde?\r\xaa\xb0\x90H\x1d\x13\xee\x01'
        type                           = ForceGetTaskResult
        timestamp                      = 1523876692
        encrypted                      = False
        sig                            = b'\xeeC\xb4\xa6E\xf7J\x14ci\x8be\xa9!\x8e-P\x86\xfa\x00\r\xdb\x8e\x0b\x11\xc4\x1b\xcf-s\x03\xf0\x1eg\xa8[\xf0\xe0I\xce\xf2\xbc\x01$\xc9FN<\xe07Z\x12\xa9\xc2\x99<\xcb\xf9\xfb\xa1sA\x0cB\x00'
        header                         = MessageHeader(type_=4009, timestamp=1523876692, encrypted=False)
            type                           = ReportComputedTask
            timestamp                      = 1523876692
            encrypted                      = False
            sig                            = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
            address                        = None
            computation_time               = None
            eth_account                    = None
            extra_data                     = None
            header                         = MessageHeader(type_=2004, timestamp=1523876692, encrypted=False)
            key_id                         = None
            multihash                      = None
            node_info                      = None
            node_name                      = None
            options                        = None
            package_hash                   = sha1:07082a1cdfae09e901b24ba68ad4321306529dc7
            port                           = None
            result_type                    = None
            secret                         = None
            size                           = 18
                type                           = TaskToCompute
                timestamp                      = 1523876692
                encrypted                      = False
                sig                            = b'\xb9\x00\xd6\x0crn\xd8[4\xd8N\xff\x8cP\xd3\xba\xab\x880\xc5(\xcbuR\xf84\x18?\x88\xe1"xQ`\xb8<\x10\xf0\xe7p\x8dx\x05\x99\x0b\xac?o\x1e\x85\xf6@\x01\xd1\xbf\x9eI\xa1\xee\xb2\xe7\x015X\x01'
                compute_task_def               = {'deadline': 1523891092, 'subtask_id': '85633', 'task_id': '85633existing_file'}
                concent_enabled                = True
                header                         = MessageHeader(type_=2002, timestamp=1523876692, encrypted=False)
                package_hash                   = None
                price                          = 0
                provider_ethereum_public_key   = None
                provider_id                    = None
                provider_public_key            = b'B\x92\x1b\xff\xc6\xbd%/\xd0\x86\xfa\xd1\xc6o\xd1T\xcewT\x88\x8bK$\xf4RA\x18\xa7)\x98\xec\x18C<\xfc\xec\xd1\xbf8\na\xb0&\xb3x\x15\xb9v\xc7\x9b\xec\x08"\xf2\x0f\xf4\xbd\\N\xde-\x85\xdeg'
                requestor_ethereum_public_key  = None
                requestor_id                   = None
                requestor_public_key           = b't@\x92\xe2\x03\x933j\xc4\x13\x11_+\xa6|}\xfe\xc5;\xa2\xd1\xed\xa8\xe3x\xa7\x83\xc1\x0b\x9b\x88\xb5GMN\xcc\xd9\x86\xac\xc3n~\xc1\x13\xee[\xf5-\xff\x96A+r\xb5:\xb3O\xd4\x14v)\xf7\x82\xea'
    header                         = MessageHeader(type_=4010, timestamp=1523876692, encrypted=True)

RECEIVE (http://127.0.0.1:8000/api/v1/receive/)
STATUS: 200 OK
MESSAGE:
Concent-Golem-Messages-Version = 2.3.1
    type                           = ForceGetTaskResultUpload
    timestamp                      = 1523876703
    encrypted                      = True
    sig                            = b'K\x97\xa0(\xad?\x1b\x80i\rr\x19\xcfP\x1d\xca\x95\xbb\xceS\x91p\xc7\xc4\xf0\xba[E\x01\xddH\x049@\xa6\xbb\xb75\xf3\xcc\xfbD\x02\x84\xdc\xf1\x93\x16\x00\xa9\x11\xd1\x98\x87V\xedu\xc7\xef\xa3\xc2tqf\x00'
        type                           = FileTransferToken
        timestamp                      = 1523876703
        encrypted                      = False
        sig                            = b"\xbe\xd8\xe4\xe1\xc9&G?\xf3\xca\xeb%\xda'\xfe\x18\xb07\x98\xfd\xf4`\xfbG\x12W\x12f\x9c\xd2,\x83Y\xbd\x7f\n\x92\x92r\xe7q\x11lV\x1bh\x81\xf0$[\xb08M\xccRe\t\xee\x04\xc4w1\xd8k\x01"
        authorized_client_public_key   = b'QpIb/8a9JS/QhvrRxm/RVM53VIiLSyT0UkEYpymY7BhDPPzs0b84CmGwJrN4Fbl2x5vsCCLyD/S9XE7eLYXeZw=='
        files                          = [{'checksum': 'sha1:07082a1cdfae09e901b24ba68ad4321306529dc7', 'path': 'blender/result/85633existing_file/85633existing_file.85633.zip', 'size': 18}]
        header                         = MessageHeader(type_=4005, timestamp=1523876703, encrypted=False)
        operation                      = upload
        storage_cluster_address        = http://devel.concent.golem.network/
        subtask_id                     = 85633
        token_expiration_deadline      = 1523905492
        type                           = ForceGetTaskResult
        timestamp                      = 1523876703
        encrypted                      = False
        sig                            = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
        header                         = MessageHeader(type_=4009, timestamp=1523876703, encrypted=False)
            type                           = ReportComputedTask
            timestamp                      = 1523876692
            encrypted                      = False
            sig                            = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
            address                        = None
            computation_time               = None
            eth_account                    = None
            extra_data                     = None
            header                         = MessageHeader(type_=2004, timestamp=1523876692, encrypted=False)
            key_id                         = None
            multihash                      = None
            node_info                      = None
            node_name                      = None
            options                        = None
            package_hash                   = sha1:07082a1cdfae09e901b24ba68ad4321306529dc7
            port                           = None
            result_type                    = None
            secret                         = None
            size                           = 18
                type                           = TaskToCompute
                timestamp                      = 1523876692
                encrypted                      = False
                sig                            = b'\xb9\x00\xd6\x0crn\xd8[4\xd8N\xff\x8cP\xd3\xba\xab\x880\xc5(\xcbuR\xf84\x18?\x88\xe1"xQ`\xb8<\x10\xf0\xe7p\x8dx\x05\x99\x0b\xac?o\x1e\x85\xf6@\x01\xd1\xbf\x9eI\xa1\xee\xb2\xe7\x015X\x01'
                compute_task_def               = {'deadline': 1523891092, 'subtask_id': '85633', 'task_id': '85633existing_file'}
                concent_enabled                = True
                header                         = MessageHeader(type_=2002, timestamp=1523876692, encrypted=False)
                package_hash                   = None
                price                          = 0
                provider_ethereum_public_key   = None
                provider_id                    = None
                provider_public_key            = b'B\x92\x1b\xff\xc6\xbd%/\xd0\x86\xfa\xd1\xc6o\xd1T\xcewT\x88\x8bK$\xf4RA\x18\xa7)\x98\xec\x18C<\xfc\xec\xd1\xbf8\na\xb0&\xb3x\x15\xb9v\xc7\x9b\xec\x08"\xf2\x0f\xf4\xbd\\N\xde-\x85\xdeg'
                requestor_ethereum_public_key  = None
                requestor_id                   = None
                requestor_public_key           = b't@\x92\xe2\x03\x933j\xc4\x13\x11_+\xa6|}\xfe\xc5;\xa2\xd1\xed\xa8\xe3x\xa7\x83\xc1\x0b\x9b\x88\xb5GMN\xcc\xd9\x86\xac\xc3n~\xc1\x13\xee[\xf5-\xff\x96A+r\xb5:\xb3O\xd4\x14v)\xf7\x82\xea'
    header                         = MessageHeader(type_=4013, timestamp=1523876703, encrypted=True)

RECEIVE (http://127.0.0.1:8000/api/v1/receive/)
STATUS: 204 No Content
Traceback (most recent call last):
  File "api-integration-force-get-task-result-test.py", line 241, in <module>
    main()
  File "api-integration-force-get-task-result-test.py", line 179, in main
    expected_content_type='application/octet-stream',
  File "/home/rwr/work/codepoets/golem/concent/concent_api/api_testing_common.py", line 108, in api_request
    validate_response_status(response.status_code, expected_status)
  File "/home/rwr/work/codepoets/golem/concent/concent_api/api_testing_common.py", line 47, in validate_response_status
    f"Expected:HTTP{expected_status}, actual:HTTP{actual_status_code}"
  File "/home/rwr/work/codepoets/golem/concent/concent_api/api_testing_common.py", line 20, in assert_condition
    raise TestAssertionException(message)
api_testing_common.TestAssertionException: Expected:HTTP200, actual:HTTP204
```

**Comment by cameel** [comment]
@rwrzesien Is this still broken?

**Comment by rwrzesien** [comment]
@cameel Yes, those tests are currently still failing (or failing again). I can't tell when they exactly started failing because I have a feeling they are not being run before every merge. We should somehow include them in our merging process.

**Comment by kbeker** [comment]
I checked now locally and everything is working properly. Tomorrow I will check it on cluster

**Comment by dybi** [comment]
seems outdated - closing
