### ISSUE TITLE
SCI fails to connect to geth on the cluster and crashes the server in the ACCEPTANCE and PAYMENT use cases

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#353]
Test `api-integration-force-accept-or-reject-results-test.py` and `api-integration-force-payment.py` returns Http500 when cluster using real backend_sci. Error doesn't occur locally when geth is working, and ConcentRPC is connected

```python 
STATUS: 500 Internal Server Error
MESSAGE:
Concent-Golem-Messages-Version = 2.7.0
{'error_message': 'Something went wrong, sorry', 
'error_code': 'concent.application_crash', 'stack_trace': 'Traceback (most recent call last):\n  File "/srv/http/virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File "/usr/lib/python3.6/contextlib.py", line 52, in inner\n    return func(*args, **kwds)\n  File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n  File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner\n    return func(request, *args, **kwargs)\n  File "/srv/http/concent_api/utils/decorators.py", line 93, in wrapper\n    return view(request, golem_message, client_public_key, *args, *kwargs)\n  File "/srv/http/concent_api/utils/decorators.py", line 106, in wrapper\n    response_from_view = view(request, client_message, client_public_key, *args, **kwargs)\n  File "/srv/http/concent_api/core/views.py", line 33, in send\n    return handle_message(client_message)\n  File "/srv/http/concent_api/core/message_handlers.py", line 1249, in handle_message\n    return handle_send_force_subtask_results(client_message)\n  File "/srv/http/concent_api/core/message_handlers.py", line 389, in handle_send_force_subtask_results\n    pending_value           = client_message.ack_report_computed_task.report_computed_task.task_to_compute.price,\n  File "/srv/http/concent_api/core/payments/base.py", line 15, in wrapper\n    return func(backend, *args, **kwargs)\n  File "/srv/http/concent_api/core/payments/base.py", line 61, in is_account_status_positive\n    pending_value           = pending_value,\n  File "/srv/http/concent_api/core/payments/sci_backend.py", line 81, in is_account_status_positive\n    client_acc_balance = ConcentRPC().get_deposit_value(client_eth_address)  # type: ignore  # pylint: disable=no-member\n  File "/srv/http/concent_api/utils/singleton.py", line 13, in __new__\n    lambda tx: tx.sign(settings.CONCENT_ETHEREUM_PRIVATE_KEY)\n  File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 43, in new_sci_rpc\n    return new_sci(Web3(HTTPProvider(rpc)), address, tx_sign, chain)\n  File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 51, in new_sci\n    _ensure_connection(web3)\n  File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 73, in _ensure_connection\n    if web3.isConnected():\n  File "/srv/http/virtualenv/lib/python3.6/site-packages/web3/main.py", line 232, in isConnected\n    if provider.isConnected():\n  File "/srv/http/virtualenv/lib/python3.6/site-packages/web3/providers/base.py", line 80, in isConnected\n    assert \'error\' not in response\nAssertionError\n'}
test_case_4b_requestor_accepts_subtaks_results: FAILED
Expected:HTTP202, actual:HTTP500
```

**Comment by cameel** [comment]
@kbeker When reporting please try to present information in a way that's easy to analyze for someone reading the issue. Having the traceback in a readable form would be useful:

``` python
Traceback (most recent call last):
  File "/srv/http/virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/srv/http/concent_api/utils/decorators.py", line 93, in wrapper
    return view(request, golem_message, client_public_key, *args, *kwargs)
  File "/srv/http/concent_api/utils/decorators.py", line 106, in wrapper
    response_from_view = view(request, client_message, client_public_key, *args, **kwargs)
  File "/srv/http/concent_api/core/views.py", line 33, in send
    return handle_message(client_message)
  File "/srv/http/concent_api/core/message_handlers.py", line 1249, in handle_message
    return handle_send_force_subtask_results(client_message)
  File "/srv/http/concent_api/core/message_handlers.py", line 389, in handle_send_force_subtask_results
    pending_value           = client_message.ack_report_computed_task.report_computed_task.task_to_compute.price,
  File "/srv/http/concent_api/core/payments/base.py", line 15, in wrapper
    return func(backend, *args, **kwargs)
  File "/srv/http/concent_api/core/payments/base.py", line 61, in is_account_status_positive
    pending_value           = pending_value,
  File "/srv/http/concent_api/core/payments/sci_backend.py", line 81, in is_account_status_positive
    client_acc_balance = ConcentRPC().get_deposit_value(client_eth_address)  # type: ignore  # pylint: disable=no-member
  File "/srv/http/concent_api/utils/singleton.py", line 13, in __new__
    lambda tx: tx.sign(settings.CONCENT_ETHEREUM_PRIVATE_KEY)
  File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 43, in new_sci_rpc
    return new_sci(Web3(HTTPProvider(rpc)), address, tx_sign, chain)
  File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 51, in new_sci
    _ensure_connection(web3)
  File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 73, in _ensure_connection
    if web3.isConnected():
  File "/srv/http/virtualenv/lib/python3.6/site-packages/web3/main.py", line 232, in isConnected
    if provider.isConnected():
  File "/srv/http/virtualenv/lib/python3.6/site-packages/web3/providers/base.py", line 80, in isConnected
    assert 'error' not in response
AssertionError
```

**Comment by cameel** [comment]
What we know so far:
- SCI uses web3 which tries to connect to geth, and fails.
- It's not clear if it manages to connect. We only know that it does get a `response` object but expects the `error` field on it which is not present.
- Connection problem is likely but the error is different from the one we get if we try to reproduce a connection problem in development (`raise Exception('Could not connect to geth: {}'.format(web3.providers))`).
- One theory is that geth is refusing connection due to the recently added `--rpcvhosts` option (see https://github.com/golemfactory/concent-deployment/pull/117). @bartoszbetka will try to confirm this.
