### ISSUE TITLE
Non-numeric task IDs crash Concent API

### ISSUE THREAD

**Issue by jiivan** [golemfactory/concent#55]
I've received undefined 500 response. Test transcript follows:
```
Prepared message: ForceReportComputedTask(timestamp=1516288707, encrypted=False, sig=None, slots=[['task_to_compute', TaskToCompute(timestamp=1516288707, encrypted=False, sig=None, slots=[['compute_task_def', {'task_id': 'a1', 'subtask_id': 'a1/1', 'deadline': 1516288717}]])], ['result_hash', 'sha1:6597eb6497f74f425c7ebacd712562cc9234697e']])
Sending to concent...
DEBUG    [golem.network.concent.client       ] send_to_concent(): Encrypting msg ForceReportComputedTask(timestamp=1516288707, encrypted=False, sig=None, slots=[['task_to_compute', TaskToCompute(timestamp=1516288707, encrypted=False, sig=None, slots=[['compute_task_def', {'task_id': 'a1', 'subtask_id': 'a1/1', 'deadline': 1516288717}]])], ['result_hash', 'sha1:6597eb6497f74f425c7ebacd712562cc9234697e']])
DEBUG    [golem.network.concent.client       ] send_to_concent(): data: b'\x0f\xa1\x00\x00\x00\x00Z`\xba\xc3\x01K\x7f\xa5J\x00R\xfa\xc5\x0e=\xe7\x16\xd4\xf5o\x16\x05\xe3\x06T:s\\\xd2\x9b\x84\xaf \xec\xe5\xb2\x87/?*o\xc1\xeb\xcb\xc9ob\xe8\x84r\xb9[\xdcw\x06\xda3\x16\xa9\xfd\xfaKz\t\xe2\xbc\x96\xc2\xdf\x00\x04\x98\xb5\xde!!\xae\xb4Y!#\x18\xce\xf3e\xbd\xf4\xeb\xc425J/V\x9b0\x1d\xec@\xeb\x89\xa2\xdb\x90\x08m\xff\xb74:7\xd1\xd7Q\xbb\xe4\x1a>\x95O\xc4Hy\x94\xf9\x9d\x9d\xea\xf5\xdd\x85XF\xbc|l\x97\xd4\xf4wz\xf7\xe1\xa1\x82\xc4\xbaI\x16s\xf3\x87\x18\xd3\xa0\xd1\xa8\xee\x8a\xbf\x15\x8d\xb5\x0ct\x127W\xf5\r\xefE@\xc3\xa2)\xb43\x99\xa4\xcf\x11\x19\x93\x00\xe5\x8d\xcbC<k\x1bf\xac\x85\x95\x00q\xefh\xa5W\xeb\xd18\xbf\xbe~\xc9/\xf6]Ku\xe67\xd6:\xe9\x9bF\xbb\xc8\x9a\x15\x81\xef\xd3o\xf8\xa7{x\x1b\x8e\xb5\xac1\x87P\xd7\x12E\xde\x92\xba\xde\xe2fT\t0\x03\xea\xd8%\x8c>m\x17 }\xed\xb1#:\x12\xff\x8a\x11R\x87l\x01\x92y\xee\x1ey\xd5\xbe\xe7C\xeaF\x92\x94\x8a\x95\xa8\x18&r\x80\xf0\xf2\x18N4\x11\xad\xc7&3\xb5d\xc5\x81\xb9\xfc\xa9s\xe9\x9a\x88\xdf\xcdP9P\xc5z\xf5\x93&|<\xd4\xadW\xa9U\xdftf\x95\xb9\xcdLo<R\xa8&\xbd(g\xed\xfd\x82\xab\xfa`\xc4\xd7\x05\xf7\xb9\xea\xa8\xb1\xbd\x11\xd6\xbc\xe5\x1a\x052\x95\x8a\xc7\xc7+5[\xb3\x9d\xeb)\xccz\xa9\xdexc\xe5W\xcd&\xde\xfa\x82\xdf\x90y \x0eVG\xe8\xa2+'
DEBUG    [golem.network.concent.client       ] send_to_concent(): POST 'http://staging.concent.golem.network/api/v1/send/' hdr: {'Content-Type': 'application/octet-stream', 'Concent-Client-Public-Key': b'9RftQn3tupVtGo76m6f1dhJD0oQJxKAwkT2JqB5FEU+5byFKklI3iPhhRhsYarxzoutzxAcb6pE/8qMmeMdB3g==', 'X-Golem-Messages': '1.4.1'}
WARNING  [golem.network.concent.client       ] Concent failed with:
status 500
headers: {'Server': 'nginx/1.13.6', 'Date': 'Thu, 18 Jan 2018 15:18:28 GMT', 'Content-Type': 'text/html', 'Content-Length': '27', 'Connection': 'keep-alive', 'Concent-Golem-Messages-Version': '1.4.1', 'Vary': 'Cookie', 'X-Frame-Options': 'SAMEORIGIN'}
body: '<h1>Server Error (500)</h1>'
```

**Comment by cameel** [comment]
It looks like the issue with non-numeric task IDs is back. I see that the validation has been removed but the logic has not been updated at the same time to be able to handle such IDs.

@rwrzesien We need to change the type of the database field. Also, add tests that check our views with non-numeric IDs.

Another thing is that it might be useful to configure the development and staging clusters to return a bit more info on failures. For example the stack trace. We probably don't want to give out that much info in production but in development it's not a big issue and should be useful. Right now the client does not even get an hint about the cause of the problem. I'll create a separate issue for it.

### Traceback from the cluster
``` python
 Traceback (most recent call last):
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/http/concent_api/utils/api_view.py", line 59, in wrapper
    response_from_view = view(request, message, *args, **kwargs)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/srv/http/concent_api/core/views.py", line 29, in send
    if Message.objects.filter(task_id = client_message.task_to_compute.compute_task_def['task_id']).exists():
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/srv/http/virtualenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1853, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'a1'
```

**Comment by cameel** [comment]
An issue for better error responses added: #57

**Comment by cameel** [comment]
@jiivan What is the range of supported types for task IDs? In case of strings, what is the maximum length? 

Would it be possible to settle on a single type for this field? Enforcing a string here would simplify storing it in a database with a predefined schema. A sensible length limit would also allow us to easily protect against stupid attacks like someone trying to store gigabytes of data in that single field and making our lookups very inefficient.

**Comment by jiivan** [comment]
It's a string (`str(uuid.uuid4())`). Which means that it's 36 characters long. I'd advise to set limit to 128 chars, because single uuid may not be enough soon.

**Comment by cameel** [comment]
So can we agree that an ID is always going to be a string no longer than 128 characters? I mean, on our side it's just a matter of adding a validation but I want to be sure that we don't suddenly start getting valid messages produced by Golem that don't satisfy this condition. golem-messages should have some kind of validation against that.

**Comment by jiivan** [comment]
Created and issue for that.
