### ISSUE TITLE
Updating geth to version v1.8.11 causes `replacement transaction underpriced` error in `api-integration-force-report-computed-task-test.py`

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent#605]
The problem occurs only when `api-integration-force-report-computed-task-test.py` test is running  after update geth to the new version. It occurs since  `v1.8.9` release.
```
 Traceback (most recent call last): File "/srv/http/virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py",
line 185, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python3.6/contextlib.py", line 52, in inner return func(*args, **kwds)
File "/srv/http/concent_api/common/decorators.py", line 275, in wrapper return _function(*args, **kwargs)
File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view return view_func(*args, **kwargs)
File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner return func(request, *args, **kwargs)
File "/srv/http/concent_api/common/decorators.py", line 158, in wrapper return view(request, golem_message, client_public_key, *args, *kwargs)
File "/srv/http/concent_api/common/decorators.py", line 174, in wrapper response_from_view = view(request, client_message, client_public_key, *args, **kwargs)
File "/srv/http/concent_api/common/decorators.py", line 286, in wrapper response_from_view = view(request, golem_message, client_public_key)
File "/srv/http/concent_api/core/views.py", line 41, in send return handle_message(client_message)
File "/srv/http/concent_api/core/message_handlers.py", line 1422, in handle_message return handle_send_force_subtask_results(client_message)
File "/srv/http/concent_api/core/message_handlers.py", line 495, in handle_send_force_subtask_results payment_ts=current_time,
File "/srv/http/concent_api/core/payments/base.py", line 15, in wrapper return func(backend, *args, **kwargs)
File "/srv/http/concent_api/core/payments/base.py", line 49, in make_force_payment_to_provider payment_ts = payment_ts,
File "/srv/http/concent_api/core/payments/sci_backend.py", line 70, in make_force_payment_to_provider closure_time = payment_ts,
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/implementation.py", line 562, in force_payment self.GAS_FORCE_PAYMENT,
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/implementation.py", line 322, in _create_and_send_transaction return self._sign_and_send_transaction(tx)
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/implementation.py", line 298, in _sign_and_send_transaction return self._geth_client.send(tx)
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/client.py", line 94, in send return self.web3.eth.sendRawTransaction(hex_data)
File "/srv/http/virtualenv/lib/python3.6/site-packages/web3/eth.py", line 227, in sendRawTransaction [raw_transaction],
File "/srv/http/virtualenv/lib/python3.6/site-packages/web3/manager.py",
line 96, in request_blocking raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}

```

**Comment by PaweuB** [comment]
Added in Pivotal:
https://www.pivotaltracker.com/story/show/158861271
