### ISSUE TITLE
SCI fails to connect to geth on the cluster after update to `1.4.1` version

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent#607]
We don't know exactly why SCI fails to connect to geth on the cluster. The problem may occur on the`concent` or `concent-deployment` side.

```
Traceback (most recent call last): File "/srv/http/virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py",
line 185, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python3.6/contextlib.py", line 52, in inner return func(*args, **kwds)
File "/srv/http/concent_api/common/decorators.py", line 275, in wrapper return _function(*args, **kwargs)
File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view return view_func(*args, **kwargs)
File "/srv/http/virtualenv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner return func(request, *args, **kwargs)
File "/srv/http/concent_api/common/decorators.py", line 158, in wrapper return view(request, golem_message, client_public_key, *args, *kwargs)
File "/srv/http/concent_api/common/decorators.py", line 174, in wrapper response_from_view = view(request, client_message, client_public_key, *args, **kwargs)
File "/srv/http/concent_api/common/decorators.py", line 286, in wrapper response_from_view = view(request, golem_message, client_public_key)
File "/srv/http/concent_api/core/views.py", line 41, in send return handle_message(client_message)
File "/srv/http/concent_api/core/message_handlers.py", line 1431, in handle_message return handle_send_force_payment(client_message)
File "/srv/http/concent_api/core/message_handlers.py", line 725, in handle_send_force_payment transaction_type = TransactionType.BATCH,
File "/srv/http/concent_api/core/payments/base.py", line 15, in wrapper return func(backend, *args, **kwargs)
File "/srv/http/concent_api/core/payments/base.py", line 33, in get_list_of_payments transaction_type = transaction_type,
File "/srv/http/concent_api/core/payments/sci_backend.py", line 25, in get_list_of_payments concent_rpc = ConcentRPC()
File "/srv/http/concent_api/common/singleton.py", line 13, in __new__ lambda tx: tx.sign(settings.CONCENT_ETHEREUM_PRIVATE_KEY)
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 48, in new_sci_rpc return new_sci(datadir, Web3(HTTPProvider(rpc)), address, tx_sign, chain)
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 62, in new_sci _ensure_connection(web3)
File "/srv/http/virtualenv/src/golem-smart-contracts-interface/golem_sci/factory.py", line 95, in _ensure_connection
raise Exception('Could not connect to geth: {}'.format(web3.providers))
Exception: Could not connect to geth: [<web3.providers.rpc.HTTPProvider object at 0x7f2454adbd68>]
```

**Comment by cameel** [comment]
Please make `ConcentRPC()` log connection parameters in its constructor (at the DEBUG level). We need to see if SCI is getting the right address.

**Comment by PaweuB** [comment]
Added in Pivotal:
https://www.pivotaltracker.com/story/show/158861257
