### ISSUE TITLE
api-test crashes with Attribute error if the server responds with HTTP 500

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#83]
When Concent API responds with HTTP 500, `api-test.py` crashes with `AttributeError`.

This happens when running `api-test.py` against the current staging server. 

### Output
```
RECEIVE (http://staging.concent.golem.network/api/v1/receive/)
STATUS: 500 Internal Server Error
MESSAGE:
RAW RESPONSE: Unexpected content-type of response message

Traceback (most recent call last):
  File "./api-test.py", line 203, in <module>
    main()
  File "./api-test.py", line 180, in main
    create_reject_data(task_id + 1), {
  File "./api-test.py", line 85, in create_reject_data
    reject_report_computed_task.reason              = RejectReportComputedTask.Reason.TASK_TIME_LIMIT_EXCEEDED
AttributeError: type object 'RejectReportComputedTask' has no attribute 'Reason'
```

**Comment by dybi** [comment]
Seems it does not reproduce anymore. Closing.
