### ISSUE TITLE
Gunicorn workers from concent-api app sometimes occurs timeout when payment must be done.

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent#844]
It's look like signing service not work always properly. To reproduce error run multiple times:  `api-integration-force-payment.py` or `api-integration-force-accept-or-reject-results-test.py`. 
They return:
```
STATUS: 502 Bad Gateway
MESSAGE:
Traceback (most recent call last):
  File "./api-integration-force-payment.py", line 291, in <module>
    run_tests(globals())
  File "/home/track/Dev/concenttt/concent/concent_api/api_testing_common.py", line 306, in run_tests
    **additional_arguments
  File "/home/track/Dev/concenttt/concent/concent_api/api_testing_common.py", line 288, in execute_tests
    test(task_id=str(uuid.uuid4()), subtask_id=str(uuid.uuid4()), **kwargs)
  File "/home/track/Dev/concenttt/concent/concent_api/api_testing_common.py", line 66, in __call__
    return self._function(*args, **kwargs)
  File "./api-integration-force-payment.py", line 115, in test_case_2d_send_correct_force_payment
    expected_content_type='application/octet-stream',
  File "/home/track/Dev/concenttt/concent/concent_api/api_testing_common.py", line 183, in api_request
    _print_response(private_key, public_key, response)
  File "/home/track/Dev/concenttt/concent/concent_api/api_testing_common.py", line 205, in _print_response
    print(f'Concent-Golem-Messages-Version = {response.headers["concent-golem-messages-version"]}')
  File "/home/track/Dev/concenttt/con/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'concent-golem-messages-version'
```
concent-api gunicorn:
```
E  14:10:34 ERROR    | Trying to remove PendingEthereumTransaction with nonce 4373 but it does not exist. 
 
E  14:10:34 ERROR    | Trying to remove PendingEthereumTransaction with nonce 4373 but it does not exist. 
 
F  [2018-09-21 14:10:34 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
 
E  14:10:34 ERROR    | Trying to remove PendingEthereumTransaction with nonce 4373 but it does not exist. 
 
E  14:10:34 ERROR    | Trying to remove PendingEthereumTransaction with nonce 4373 but it does not exist. 
 

```
middleman logs:
```
14:10:48 INFO     | Client has closed the connection: 119. Ending 'request_producer' coroutine
14:10:49 INFO     | Removing response queue for connection ID: 111. 
14:10:49 INFO     | Removing response queue for connection ID: 112. 
14:10:50 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539050, encrypted=False)
14:10:50 INFO     | Received message from Concent: request ID = 4, connection ID = 120
14:10:50 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539050, encrypted=False)
14:10:50 INFO     | Received message from Signing Service: request ID = 120
14:10:50 INFO     | Message (request ID=4) for Concent has been sent for connection ID=120
14:10:50 INFO     | Client has closed the connection: 120. Ending 'request_producer' coroutine
14:10:50 INFO     | Removing response queue for connection ID: 113. 
14:10:51 INFO     | Removing response queue for connection ID: 114. 
14:10:51 INFO     | Removing response queue for connection ID: 115. 
14:10:51 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539051, encrypted=False)
14:10:51 INFO     | Received message from Concent: request ID = 12, connection ID = 121
14:10:51 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539051, encrypted=False)
14:10:51 INFO     | Received message from Signing Service: request ID = 121
14:10:51 INFO     | Message (request ID=12) for Concent has been sent for connection ID=121
14:10:51 INFO     | Client has closed the connection: 121. Ending 'request_producer' coroutine
14:10:52 INFO     | Removing response queue for connection ID: 116. 
14:10:52 INFO     | Removing response queue for connection ID: 117. 
14:10:52 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539052, encrypted=False)
14:10:52 INFO     | Received message from Concent: request ID = 16, connection ID = 122
14:10:52 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539052, encrypted=False)
14:10:52 INFO     | Received message from Signing Service: request ID = 122
14:10:52 INFO     | Message (request ID=16) for Concent has been sent for connection ID=122
14:10:52 INFO     | Client has closed the connection: 122. Ending 'request_producer' coroutine
14:10:52 INFO     | Removing response queue for connection ID: 118. 
14:10:53 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539053, encrypted=False)
14:10:53 INFO     | Received message from Concent: request ID = 17, connection ID = 123
14:10:53 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539053, encrypted=False)
14:10:53 INFO     | Received message from Signing Service: request ID = 123
14:10:53 INFO     | Message (request ID=17) for Concent has been sent for connection ID=123
14:10:53 INFO     | Client has closed the connection: 123. Ending 'request_producer' coroutine
14:10:53 INFO     | Removing response queue for connection ID: 119. 
14:10:54 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539054, encrypted=False)
14:10:54 INFO     | Received message from Concent: request ID = 18, connection ID = 124
14:10:54 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539054, encrypted=False)
14:10:54 INFO     | Received message from Signing Service: request ID = 124
14:10:54 INFO     | Message (request ID=18) for Concent has been sent for connection ID=124
14:10:54 INFO     | Client has closed the connection: 124. Ending 'request_producer' coroutine
14:10:55 INFO     | Removing response queue for connection ID: 120. 
14:10:56 INFO     | Removing response queue for connection ID: 121. 
14:10:57 INFO     | Removing response queue for connection ID: 122. 
14:10:58 INFO     | Removing response queue for connection ID: 123. 
14:10:58 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539058, encrypted=False)
14:10:58 INFO     | Received message from Concent: request ID = 11, connection ID = 125
14:10:58 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539058, encrypted=False)
14:10:58 INFO     | Received message from Signing Service: request ID = 125
14:10:58 INFO     | Message (request ID=11) for Concent has been sent for connection ID=125
14:10:58 INFO     | Client has closed the connection: 125. Ending 'request_producer' coroutine
14:10:59 INFO     | Removing response queue for connection ID: 124. 
14:10:59 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539059, encrypted=False)
14:10:59 INFO     | Received message from Concent: request ID = 9, connection ID = 126
14:10:59 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539059, encrypted=False)
14:10:59 INFO     | Received message from Signing Service: request ID = 126
14:10:59 INFO     | Message (request ID=9) for Concent has been sent for connection ID=126
14:10:59 INFO     | Client has closed the connection: 126. Ending 'request_producer' coroutine
14:11:00 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539060, encrypted=False)
14:11:00 INFO     | Received message from Concent: request ID = 12, connection ID = 127
14:11:00 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539060, encrypted=False)
14:11:00 INFO     | Received message from Signing Service: request ID = 127
14:11:00 INFO     | Message (request ID=12) for Concent has been sent for connection ID=127
14:11:00 INFO     | Client has closed the connection: 127. Ending 'request_producer' coroutine
14:11:01 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539061, encrypted=False)
14:11:01 INFO     | Received message from Concent: request ID = 10, connection ID = 128
14:11:01 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539061, encrypted=False)
14:11:01 INFO     | Received message from Signing Service: request ID = 128
14:11:01 INFO     | Message (request ID=10) for Concent has been sent for connection ID=128
14:11:01 INFO     | Client has closed the connection: 128. Ending 'request_producer' coroutine
14:11:02 DEBUG    | deserialize_header(): MessageHeader(type_=9001, timestamp=1537539062, encrypted=False)
14:11:02 INFO     | Received message from Concent: request ID = 17, connection ID = 129
14:11:02 DEBUG    | deserialize_header(): MessageHeader(type_=9002, timestamp=1537539062, encrypted=False)
14:11:02 INFO     | Received message from Signing Service: request ID = 129
14:11:02 INFO     | Message (request ID=17) for Concent has been sent for connection ID=129
14:11:02 INFO     | Client has closed the connection: 129. Ending 'request_producer' coroutine
14:11:03 INFO     | Removing response queue for connection ID: 125. 
14:11:04 INFO     | Removing response queue for connection ID: 126. 
14:11:05 INFO     | Removing response queue for connection ID: 127. 
14:11:06 INFO     | Removing response queue for connection ID: 128. 
14:11:07 INFO     | Removing response queue for connection ID: 129. 

```

signing service logs:
```
14:10:01 INFO     | Sending Middleman protocol message with request_id: 93.
14:10:02 INFO     | Sending Middleman protocol message with request_id: 94.
14:10:02 INFO     | Sending Middleman protocol message with request_id: 95.
14:10:02 INFO     | Sending Middleman protocol message with request_id: 96.
14:10:03 INFO     | Sending Middleman protocol message with request_id: 97.
14:10:03 INFO     | Sending Middleman protocol message with request_id: 98.
14:10:04 INFO     | Deserializing received Middleman protocol message failed with exception: Frame signature does not match its content..
14:10:04 INFO     | Sending Middleman protocol message with request_id: 0.
14:10:34 INFO     | Sending Middleman protocol message with request_id: 100.
14:10:36 INFO     | Sending Middleman protocol message with request_id: 101.
14:10:37 INFO     | Sending Middleman protocol message with request_id: 102.
14:10:38 INFO     | Sending Middleman protocol message with request_id: 103.
14:10:38 INFO     | Sending Middleman protocol message with request_id: 104.
14:10:39 INFO     | Sending Middleman protocol message with request_id: 105.
14:10:39 INFO     | Sending Middleman protocol message with request_id: 106.
14:10:40 INFO     | Sending Middleman protocol message with request_id: 107.
14:10:40 INFO     | Sending Middleman protocol message with request_id: 108.
14:10:41 INFO     | Sending Middleman protocol message with request_id: 109.
14:10:43 INFO     | Sending Middleman protocol message with request_id: 110.
14:10:44 INFO     | Sending Middleman protocol message with request_id: 111.
14:10:44 INFO     | Sending Middleman protocol message with request_id: 112.
14:10:45 INFO     | Sending Middleman protocol message with request_id: 113.
14:10:45 INFO     | Sending Middleman protocol message with request_id: 114.
14:10:46 INFO     | Sending Middleman protocol message with request_id: 115.
14:10:46 INFO     | Sending Middleman protocol message with request_id: 116.
14:10:47 INFO     | Sending Middleman protocol message with request_id: 117.
14:10:47 INFO     | Sending Middleman protocol message with request_id: 118.
14:10:48 INFO     | Sending Middleman protocol message with request_id: 119.
14:10:50 INFO     | Sending Middleman protocol message with request_id: 120.
14:10:51 INFO     | Sending Middleman protocol message with request_id: 121.
14:10:52 INFO     | Sending Middleman protocol message with request_id: 122.
14:10:53 INFO     | Sending Middleman protocol message with request_id: 123.
14:10:54 INFO     | Sending Middleman protocol message with request_id: 124.
14:10:58 INFO     | Sending Middleman protocol message with request_id: 125.
14:10:59 INFO     | Sending Middleman protocol message with request_id: 126.
14:11:00 INFO     | Sending Middleman protocol message with request_id: 127.
14:11:01 INFO     | Sending Middleman protocol message with request_id: 128.
14:11:02 INFO     | Sending Middleman protocol message with request_id: 129.

```

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160688368
