### ISSUE TITLE
Internal Server Error during testing which are touching bankster

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#913]
Probably error occurred because of assumption that `force_payment` return `Transaction` object. Currently it returns hash of transacation. 

```python
Traceback (most recent call last):
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/common/decorators.py", line 295, in wrapper
    return _function(*args, **kwargs)
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/common/decorators.py", line 168, in wrapper
    return view(request, golem_message, client_public_key, *args, *kwargs)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/common/decorators.py", line 190, in wrapper
    response_from_view = view(request, client_message, client_public_key, *args, **kwargs)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/common/decorators.py", line 306, in wrapper
    response_from_view = view(request,  golem_message, client_public_key)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/core/views.py", line 46, in send
    return handle_message(client_message)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/core/message_handlers.py", line 1396, in handle_message
    return handle_send_force_subtask_results(client_message)
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/core/message_handlers.py", line 533, in handle_send_force_subtask_results
    subtask_cost=task_to_compute.price,
  File "/home/karolb/GITHUB/codepoets/concent/concent_api/core/payments/bankster.py", line 137, in finalize_payment
    tx_hash=transaction.hash,
AttributeError: 'str' object has no attribute 'hash'
11:01:34 ERROR    | "POST /api/v1/send/ HTTP/1.1" 500 2198
11:01:35 ERROR    | Sentry responded with an error: <urlopen error [Errno -2] Name or service not known> (url: https://dupa.sd.sd/api/2/store/)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/raven/utils/http.py", line 31, in connect
    timeout=self.timeout,
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/karolb/.virtualenvs/concent/lib/python3.6/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
11:01:35 ERROR    | ['Internal Server Error: /api/v1/send/', '  File "django/core/handlers/base.py", line 185, in _get_response', '  File "python3.6/contextlib.py", line 52, in inner', '  File "common/decorators.py", line 295, in wrapper', '  File "django/views/decorators/csrf.py", line 58, in wrapped_view', '  File "django/views/decorators/http.py", line 40, in inner', '  File "common/decorators.py", line 168, in wrapper', '  File "common/decorators.py", line 190, in wrapper', '  File "common/decorators.py", line 306, in wrapper', '  File "core/views.py", line 46, in send', '  File "core/message_handlers.py", line 1396, in handle_message', '  File "core/message_handlers.py", line 533, in handle_send_force_subtask_results', '  File "core/payments/bankster.py", line 137, in finalize_payment']
```

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161544558
