### ISSUE TITLE
Signing Service fails instead of printing a friendly error message when it gets an invalid base64 value

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent#950]
There is a case when someone make mistake when running signing service by changing the order of `concent_cluster_host` and `concent_public_key` variables. By running:

```
./signing_service.sh "85cZzVjahnRpUBwm0zlNnqTdYom1LF1P1WNShLg17cmhN2UssnPrCjHKTi5susO3wrr/q07eswumbL82b4HgOw==" "127.0.0.1" --ethereum-private-key-from-env --signing-service-private-key-from-env
```
The stacktrace look like this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/concent/signing_service/signing_service/signing_service.py", line 614, in <module>
    main()
  File "/home/vagrant/concent/signing_service/signing_service/signing_service.py", line 581, in main
    args = _parse_arguments()
  File "/home/vagrant/concent/signing_service/signing_service/signing_service.py", line 574, in _parse_arguments
    return parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1963, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1940, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/vagrant/concent/signing_service/signing_service/utils.py", line 113, in __call__
    self.const = b64decode(self.const)
  File "/home/vagrant/virtualenv/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
The error message indicates fault in base64 variables, but it's actually tries to decode "127.0.0.1".

**Comment by cameel** [comment]
@dybi Proposed removing all positional arguments and replacing them with keywords. I'm fine with that but this is a separate problem. The issue here is that an invalid base64 value results in a fail and stacktrace. It should fail with a comprehensible error messages instead and indicate which parameter got the invalid value.
